### ISSUE TITLE
Shorten Links not stabled

### ISSUE THREAD

**Issue by QuasarX** [zenden2k/image-uploader#226]
Options > Shorten URL using ... feature not working stable. Some times not working (select many files)

**Comment by zenden2k** [comment]
Hi,

Can you provide the below requested information to better understand the issue:

Steps to reproduce
What steps do others need to take in order to reproduce the issue themselves?

Frequency
How frequently does this issue occur? (e.g 100% of the time, 10% of the time)

Expected output
What do you expect to occur?

Current output
What do you see instead?

**Comment by QuasarX** [comment]
Please watch video.
I tried other link shortener services (goo.gl, u.to etc) but not working.
https://vimeo.com/150470510

**Comment by zenden2k** [comment]
So this is version 1.3.1. 
It is not developed anymore. I believe that this issue doesn't exist anymore in 1.3.2 branch.

**Comment by QuasarX** [comment]
Hmm. Thanks. Using now v1.3.2
